version: '3.9'
services:
  app:
    container_name: ec-front
    build:
      dockerfile: ec/handmade-workshop/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./handmade-workshop
        target: /src
    environment:
      - NODE_ENV=development
    ports:
      - '13000:3000'
    tty: true
  db:
    image: mysql:5.7
    container_name: handmade-workshop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: handmade_workshop
    ports:
      - "13306:3306"
    volumes:
      - type: volume
        source: handmade-workshop-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./src/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql

volumes:
  handmade-workshop-db-volume: