version: '3.9'
services:
  handmade-workshop:
    container_name: ec-front
    build:
      dockerfile: ec/handmade-workshop/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./handmade-workshop
        target: /src
    environment:
      - NODE_ENV=development
    ports:
      - '13000:3000'
    tty: true
  mysql:
    container_name: handmade-workshop-db
    build:
      dockerfile: handmade-workshop/db/Dockerfile
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ec
    ports:
      - "13306:3306"
    volumes:
      - type: volume
        source: ec-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql

volumes:
  ec-db-volume: